#!/bin/sh
#
# Starts the gps daemon.
#

NAME=gpsd
DAEMON=/usr/sbin/$NAME
DEVICES="/dev/ttyACM0"
PIDFILE=/var/run/$NAME.pid
GPSD_OPTIONS="-G -n -r"

[ -x "$DAEMON" ] || exit 0

start() {
        printf 'Starting %s: ' "$NAME"
        # shellcheck disable=SC2086
        start-stop-daemon -S -q -p "$PIDFILE" --exec "$DAEMON" -- -P "$PIDFILE" $GPSD_OPTIONS "$DEVICES" && echo "OK" || echo "FAIL"
        sleep 3
        gpsctl --nmea
}
stop() {
        printf 'Stopping %s: ' "$NAME"
        start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
        rm -f $PIDFILE
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
