#!/bin/sh
case "$1" in
    start) /bin/sh /usr/sbin/libresdr-tx-nco boot;;
    stop) /bin/sh /usr/sbin/libresdr-tx-nco stop;;
    restart) /bin/sh /usr/sbin/libresdr-tx-nco stop && /bin/sh /usr/sbin/libresdr-tx-nco boot;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1;;
esac
