#!/bin/sh

[ -x /usr/bin/input-event-daemon ] || exit 0
[ -e /dev/input/event0 ] || exit 0

start() {
	printf "Starting input-event-daemon: "
	input-event-daemon && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping input-event-daemon: "
	killall input-event-daemon 2>/dev/null && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac
