################################################################################
#
# sdroxide
#
################################################################################

# Pinned commit (2026-09-18). Upstream has no tagged releases at this pin;
# bump by hand and re-check the three local patches still apply.
SDROXIDE_VERSION = df6fd098742b9e3c8e1130974e60a5bb84946e9e
SDROXIDE_SITE = https://github.com/dividebysandwich/sdroxide.git
SDROXIDE_SITE_METHOD = git
# faad2/nrsc5/rtl_433/rade_c are git submodules; sdroxide-drm and
# sdroxide-nrsc5 (which link faad2) and sdroxide-rade (which links rade_c) are
# unconditional dependencies of sdroxide-radio, so all three are always
# needed even with --no-default-features (which only drops soapy/rtl433, so
# vendor/rtl_433 alone is not actually required here, but there is no Cargo
# feature to skip fetching its submodule).
SDROXIDE_GIT_SUBMODULES = YES

# GPL-3.0-or-later overall, but the AGPL-3.0-only DeepCW crate (CW decoder,
# reached via sdroxide-digi/sdroxide-skimmer, both unconditional deps of
# sdroxide-radio) is linked into the binary. AGPL-3.0 section 13 means anyone
# who talks to sdroxide-server over the network is entitled to the complete
# corresponding source for what they are running -- relevant here precisely
# because this package's whole point is running it as a network-facing
# server. Not a build concern, but worth remembering before shipping.
SDROXIDE_LICENSE = GPL-3.0-or-later, AGPL-3.0-only (sdroxide-deepcw)
SDROXIDE_LICENSE_FILES = LICENSE

SDROXIDE_DEPENDENCIES = alsa-lib rust-wasm stunnel

# Use Buildroot's $(TARGET_CROSS), which expands to $(HOST_DIR)/bin/<prefix>-
# and adapts per toolchain: arm-none-linux-gnueabihf- for Arm GNU, or
# arm-linux- for Bootlin, or arm-buildroot-linux-gnueabihf- for internal.
# cmake/bindgen need a full absolute path, not just the prefix, hence the
# gcc/g++ suffix here (same reasoning as maia-httpd.mk).
SDROXIDE_TOOLCHAIN_GCC = $(TARGET_CROSS)gcc
SDROXIDE_TOOLCHAIN_GXX = $(TARGET_CROSS)g++

# crates/sdroxide-web (the browser client) is built here too, alongside the
# ARM server binary -- both come from the same already-downloaded, already-
# patched workspace checkout, so building it as a separate Buildroot package
# would mean a second full git clone + submodule fetch of the same ~40-crate
# tree for no benefit.
#
# Upstream builds it with `trunk`, which Buildroot has no package for (and
# which needs the same rustc >=1.95 as eframe/rten/kstring -- see 0001; the
# 2026.05 Buildroot bump is what made attempting this worthwhile at all).
# wasm-bindgen-cli does the same job -- compile-to-wasm32 plus generating the
# JS glue -- without needing a new package: it is a plain binary crate on
# crates.io, so `cargo install` here is enough, matching how maia-wasm.mk
# shells out to `cargo generate-lockfile` directly rather than wrapping it in
# its own package. Its version MUST exactly match the `wasm-bindgen` library
# version Cargo.lock resolves for crates/sdroxide-web (not just semver-
# compatible) or the generated JS refuses to load the wasm at runtime ("this
# binary is version X, but the JS was generated by wasm-bindgen version Y")
# -- re-check after every SDROXIDE_VERSION bump:
#   grep -A2 'name = "wasm-bindgen"' Cargo.lock   (after a build, in $(@D))
SDROXIDE_WASM_BINDGEN_CLI_VERSION = 0.2.127

define SDROXIDE_BUILD_CMDS
	cd $(@D) && \
	PATH="$(HOST_DIR)/bin:$$PATH" \
	BINDGEN_EXTRA_CLANG_ARGS_armv7_unknown_linux_gnueabihf="--sysroot=$(STAGING_DIR)" \
	CC_armv7_unknown_linux_gnueabihf="$(SDROXIDE_TOOLCHAIN_GCC)" \
	CXX_armv7_unknown_linux_gnueabihf="$(SDROXIDE_TOOLCHAIN_GXX)" \
	PKG_CONFIG_ALLOW_CROSS=1 \
	CFLAGS_armv7_unknown_linux_gnueabihf="-mfpu=neon" \
	CXXFLAGS_armv7_unknown_linux_gnueabihf="-mfpu=neon" \
	cargo build --release --no-default-features \
		--target armv7-unknown-linux-gnueabihf \
		--config "target.armv7-unknown-linux-gnueabihf.linker=\"$(SDROXIDE_TOOLCHAIN_GCC)\""

	PATH="$(HOST_DIR)/bin:$$PATH" \
	cargo install wasm-bindgen-cli --version $(SDROXIDE_WASM_BINDGEN_CLI_VERSION) \
		--root $(@D)/.host-tools --quiet

	cd $(@D)/crates/sdroxide-web && \
	PATH="$(HOST_DIR)/bin:$$PATH" \
	cargo build --release --target wasm32-unknown-unknown

	rm -rf $(@D)/dist-web
	mkdir -p $(@D)/dist-web
	$(@D)/.host-tools/bin/wasm-bindgen --target web \
		--out-dir $(@D)/dist-web --out-name sdroxide-web --no-typescript \
		--remove-name-section --remove-producers-section \
		$(@D)/target/wasm32-unknown-unknown/release/sdroxide-web.wasm
	cp $(@D)/crates/sdroxide-web/assets/*.js $(@D)/dist-web/
	cp $(SDROXIDE_PKGDIR)/web-index.html $(@D)/dist-web/index.html
endef

# CFLAGS_armv7_unknown_linux_gnueabihf=-mfpu=neon: the Zynq-7000 PS genuinely
# has a NEON unit, but rustc's armv7-unknown-linux-gnueabihf baseline target
# builds everything (via the `cc`/`cmake` crates' cross defaults) assuming it
# doesn't (-mfpu=vfpv3-d16). The vendored Opus (pulled in by both
# sdroxide-server and sdroxide-rade) always compiles its ARM NEON-intrinsic
# source files once <arm_neon.h> exists -- its own OPUS_MAY_HAVE_NEON/
# OPUS_ARM_MAY_HAVE_NEON options only pick which *additional* dispatch table
# to build, they never gate those files out -- so those intrinsics fail to
# compile at all without a target-wide -mfpu that actually enables NEON.
# 0003-opus-disable-runtime-neon-detection.patch is the matching Cargo-side
# half: with NEON forced on everywhere, opusic-sys's separate generic/NEON
# runtime-dispatch build has nothing left to switch between.

# The binary (tens of MB even stripped -- it embeds several neural-net models:
# DeepCW's CW decoder, DeepFilterNet3's noise reduction, RADE's FreeDV
# vocoder) does NOT go into the rootfs: that rootfs is a cpio.xz ramdisk
# decompressed whole into RAM at every boot, and this binary alone would come
# close to doubling that. Instead it's installed as an IMAGE (BINARIES_DIR),
# same mechanism board-fpga.mk uses for system_top.bit, and
# board/tezuka/common/postimage-sd.sh copies it from there onto the SD card's
# FAT boot partition alongside BOOT.bin/uImage/uramdisk.image.xz. That
# partition is what board/tezuka/common/overlay_tezuka's S20fat-mount mounts
# at /boot at runtime, so S65sdroxide (installed into the rootfs -- it is a
# few hundred bytes, not the multi-MB binary) just execs it from there
# directly; nothing needs decompressing at boot.
SDROXIDE_INSTALL_IMAGES = YES

define SDROXIDE_INSTALL_IMAGES_CMDS
	$(TARGET_STRIP) --strip-all -o $(BINARIES_DIR)/sdroxide \
		$(@D)/target/armv7-unknown-linux-gnueabihf/release/sdroxide
	rm -rf $(BINARIES_DIR)/sdroxide-web
	mkdir -p $(BINARIES_DIR)/sdroxide-web
	cp -a $(@D)/dist-web/. $(BINARIES_DIR)/sdroxide-web/
endef

# stunnel (see package/stunnel, upstream): sdroxide-server has no TLS of its
# own, and the Web Audio API refuses microphone/audio-playback access
# outside a secure context. S45sdroxide-tls-cert + stunnel-sdroxide.conf
# wrap the plain HTTP server (127.0.0.1:4950) in TLS on port 4951 with a
# throwaway self-signed cert regenerated every boot -- see those files for
# why persistent storage isn't used.
define SDROXIDE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(SDROXIDE_PKGDIR)/S65sdroxide $(TARGET_DIR)/etc/init.d/S65sdroxide
	$(INSTALL) -D -m 0755 $(SDROXIDE_PKGDIR)/S45sdroxide-tls-cert $(TARGET_DIR)/etc/init.d/S45sdroxide-tls-cert
	$(INSTALL) -D -m 0644 $(SDROXIDE_PKGDIR)/stunnel-sdroxide.conf $(TARGET_DIR)/etc/stunnel/stunnel.conf
endef

$(eval $(generic-package))
