#!/bin/sh

case "$1" in
  start)
	echo -n "Starting maia-httpd: "
        cd /root
        start-stop-daemon -S -b -q -m -p /var/run/maia-httpd.pid -x /usr/bin/maia-httpd
        cd - > /dev/null
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
        echo -n "Stopping maia-httpd: "
        start-stop-daemon -K -q -p /var/run/maia-httpd.pid 2>/dev/null
        [ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
        $0 stop
        sleep 1
        $0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
