#!/bin/sh
nfs_server=`fw_printenv -n nfs_server 2> /dev/null`

start() {
   if [[ -n $nfs_server ]]
	then
		
		echo "mounting NFS volume : $nfs_server on /mnt/nfs"		
		mkdir -p /mnt/nfs
		mount -o nolock -t nfs $nfs_server /mnt/nfs
		#ex:   fw_setenv  nfs_server "192.168.2.10:/home/linuxdev/prog"
		
	else
		
		echo "Info : No nfs to mount"
	fi
	SD_FILE="/dev/mmcblk0p1"

	if [ -e "$SD_FILE" ]; then
   		echo "Mounting SD on /mnt/sd"
		mount $SD_FILE /mnt/sd
	fi
}

stop() {

	
	echo "Stopping NFS"
	umount /mnt/nfs
	echo "Stopping SD"
	umount /mnt/sd
	
}

restart() {
	stop
	start
}

# start/stop/restart
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?



